version: '3.8'

services:
  php-fpm:
    container_name: php_container
    # UBAH BARIS DI BAWAH INI:
    build: .
    ports:
      - "9000:9000"
    volumes:
      - ./projek_wfd_2026:/code

  nginx:
    container_name: nginx_container
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./projek_wfd_2026:/code
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  db:
    container_name: mysql_container
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=lara